### ISSUE TITLE
 nodejs.TypeError: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Spark

### ISSUE THREAD

**Issue by yelianjie** [eggjs/egg-spark#3]
大佬，我node不太懂，然后按照你的例子，出现了这个错误，能看下什么原因吗？

![image](https://user-images.githubusercontent.com/15810183/182982478-dd520ebf-31d0-4ade-8c45-fe989cc124f7.png)
![image](https://user-images.githubusercontent.com/15810183/182982555-bc36b660-2c24-499c-a80e-c12d934d6917.png)

**Comment by kisnows** [comment]
需要提供可以复现问题的最小实现仓库，否则难以排查问题。

**Comment by kisnows** [comment]
参考:https://github.com/eggjs/egg/issues/3310
